# Generated by Django 4.2.9 on 2024-01-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_product_is_active_productline"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="123", max_length=255),
            preserve_default=False,
        ),
    ]
