# Generated by Django 4.2.9 on 2024-02-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_brand_is_active_category_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productline",
            name="order",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
