# Generated by Django 4.2.9 on 2024-02-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_alter_productline_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="p2", max_length=255),
            preserve_default=False,
        ),
    ]
